### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by michaelfranzl** [stolk/dutch-blunt#1]
```
./tools/fnt.py models/font.obj
```

gives

```
Traceback (most recent call last):
  File "./tools/fnt.py", line 60, in <module>
    assert len(blobs) == 128-1
AssertionError
```

My guess is that you didn't check in the most recent font.obj?

I'd like to try this 3D font, so a fix would be appreciated.

**Comment by stolk** [comment]
My apologies, I checked in the latest 3d model file as wavefront .obj, please try again.
https://github.com/stolk/dutch-blunt/commit/e1b0044a8787a47e786bb6e06a1c7a28bb27114b

**Comment by michaelfranzl** [comment]
Worked, thank you!
